---

- name: Install inotify-tools
  apt:
    name: inotify-tools

- name: Create directory for shell script
  file:
    name="~/piholesync"
    state=directory

- name: Copy script from template
  template:
    src: "piholesync.rsync.sh.j2"
    dest: "~/piholesync/piholesync.rsync.sh"