---
- hosts: nutserver
  become: yes
  roles:
    - role: nut
      nut_nut_conf:
        MODE: netserver
      nut_ups_conf:
        globals:
          maxretry: 3
          user: "{{nut_user}}"
        upses:
          ups01:
            driver: usbhid-ups #https://networkupstools.org/docs/man/usbhid-ups.html
            port: auto
            desc: Server rack UPS
            override.battery.charge.low: 20
            override.battery.charge.warning: 30
      nut_upsd_conf:
        LISTEN:
          - "{{ansible_default_ipv4.address}} 3493"
          - 127.0.0.1 3493
          - 172.16.10.2 3493
          - 172.16.10.4 3493
      nut_upsd_users:
        admin:
          password: "{{nutadminpass}}"
          actions:
            - set
            - fsd
          instcmds: all
        monitor:
          password: "{{nutmonitorpass}}"
          upsmon master: '' #special entry, doesn't follow normal ini format.

- hosts: nutclient
  become: yes
  roles:
    - role: nut
      nut_nut_conf:
        MODE: netclient
    
    #run nut driver, server, and client
