---
- hosts: nutserver
  become: yes
  roles:
    - role: nut
      nut_nut_conf:
        MODE: netserver
        UPSD_OPTIONS: '""'
        UPSMON_OPTIONS: '""'
      nut_ups_conf:
        globals:
          maxretry: 3
          user: "{{nut_user}}"
        upses:
          ups01:
            driver: usbhid-ups #https://networkupstools.org/docs/man/usbhid-ups.html
            port: auto
            serial: {{ups01serial}}
            desc: Server rack UPS
            override.battery.charge.low: 20
            override.battery.charge.warning: 30
          qnapups:
            driver: dummy-ups
            port: ups01@localhost
            desc: UPS for QNAP
#          ups02:
#            driver: usbhid-ups
#            port: auto
#            serial: #############
#            desc: Desktop UPS
      nut_upsd_conf:
        LISTEN:
          - "{{ansible_default_ipv4.address}} 3493"
          - 127.0.0.1 3493
      nut_upsd_users:
        nutadmin:
          password: "{{nutadminpass}}"
          actions:
            - set
            - fsd
          instcmds: all
        monmaster:
          password: "{{nutmonitorpass}}"
          upsmon master: '' #special entry, doesn't follow normal ini format.
        monslave:
          password: "{{nutmonitorpass}}"
          upsmon slave: '' #special entry, doesn't follow normal ini format.
        admin:
          password: "{{nutqnappass}}"
          upsmon master: ''
      nut_upsmon_conf:
        DEADTIME: 15
        FINALDELAY: 60
        HOSTSYNC: 15
        MINSUPPLIES: 1
        MONITOR:
          - "ups01@{{nutserverip}}:3493 1 monmaster {{nutmonitorpass}} master"
#          - "ups02@{{nutserverip}}:3493 1 monmaster {{nutmonitorpass}} master"
        NOCOMMWARNTIME: 300
        POLLFREQ: 5
        POLLFREQALERT: 5
        POWERDOWNFLAG: /etc/killpower
        RBWARNTIME: 43200
        NOTIFYCMD: '/etc/nut/mqttnotify/nutnotifymqtt.sh'
        NOTIFYFLAG: 
          - 'ONLINE       SYSLOG+WALL+EXEC'
          - 'ONBATT       SYSLOG+WALL+EXEC'
          - 'LOWBATT      SYSLOG+WALL+EXEC'
          - 'FSD          SYSLOG+WALL+EXEC'
          - 'COMMOK       SYSLOG+WALL+EXEC'
          - 'COMMBAD      SYSLOG+WALL+EXEC'
          - 'SHUTDOWN     SYSLOG+WALL+EXEC'
          - 'REPLBATT     SYSLOG+WALL+EXEC'
          - 'NOCOMM       SYSLOG+WALL+EXEC'
          - 'NOPARENT     SYSLOG+WALL+EXEC'
        SHUTDOWNCMD: '"/sbin/shutdown -h +0"'
        RUN_AS_USER: "{{nut_user}}"
      nut_host_conf:
        MONITOR:
          - "ups01@{{nutserverip}}:3493 \"Rack UPS\""
#          - "ups02@{{nutserverip}}:3493 \"Desktop UPS\""

- hosts: nutclient
  become: yes
  roles:
    - role: nut
      nut_nut_conf:
        MODE: netclient
        UPSD_OPTIONS: '""'
        UPSMON_OPTIONS: '""'
      nut_upsmon_conf:
        DEADTIME: 15
        FINALDELAY: 5
        HOSTSYNC: 15
        MINSUPPLIES: 1
        MONITOR:
          - "ups01@{{nutserverip}}:3493 1 monslave {{nutmonitorpass}} slave"
        NOCOMMWARNTIME: 300
        POLLFREQ: 5
        POLLFREQALERT: 5
        POWERDOWNFLAG: /etc/killpower
        RBWARNTIME: 43200
        SHUTDOWNCMD: '"/sbin/shutdown -h +0"'
        RUN_AS_USER: "{{nut_user}}"
