---
- hosts: raspberrypi3
  tasks: 
  - name: copy room assistant config from template for docker
    template:
      src: "~/ansible/room-assistant/config/template/local.yml.j2"
      dest: "/etc/room-assistant/config/local.yml"