#chrony-slave handlers

---
# handlers file for chrony setup
- name: restart crond
  become: yes
  service:
    name: crond
    state: restarted

- name: restart chronyd
  become: yes
  service:
    name: chronyd
    state: restarted