# nut/tasks/server.yml

---
- name: install nut server
  package: >
    name={{nut_server_package}}
    state=latest

- name: configure ups.conf
  template: >
    src=ups.conf.j2
    dest={{nut_config_path}}/ups.conf
    owner=root
    group={{nut_user}}
    mode=0644
  notify:
    - restart nut-server
    - restart nut-driver

- name: configure upsd.conf #to allow server to listen to other clients
  template: >
    src=upsd.conf.j2
    dest={{nut_config_path}}/upsd.conf
    owner=root
    group={{nut_user}}
    mode=0644
  notify:
    - restart nut-server

- name: configure upsd.users
  template: >
    src=upsd.users.j2
    dest={{nut_config_path}}/upsd.users
    owner=root
    group={{nut_user}}
    mode=0640
  notify:
    - restart nut-server