# nut/tasks/server.yml

---
- name: install nut server
  package: >
    name={{nut_server_package}}
    state=latest

- name: install nut cgi package
  package: >
    name={{nut_cgi_package}}
    state=latest

- name: install apache2
  package: >
    name=apache2
    state=latest

- name: configure ups.conf
  template: >
    src=ups.conf.j2
    dest={{nut_config_path}}/ups.conf
    owner=root
    group={{nut_user}}
    mode=0644
  notify:
    - restart nut-server
    - restart nut-driver

- name: configure upsd.conf #to allow server to listen to other clients
  template: >
    src=upsd.conf.j2
    dest={{nut_config_path}}/upsd.conf
    owner=root
    group={{nut_user}}
    mode=0644
  notify:
    - restart nut-server

- name: configure upsd.users
  template: >
    src=upsd.users.j2
    dest={{nut_config_path}}/upsd.users
    owner=root
    group={{nut_user}}
    mode=0640
  notify:
    - restart nut-server

- name: configure hosts.conf
  template: >
    src=hosts.conf.j2
    dest={{nut_config_path}}/hosts.conf
    owner=root
    group={{nut_user}}
    mode=0640
#  notify:
#    - restart nut-server

- name: install udev rules
  copy: >
    src=files/52-nut-usbups.rules
    dest=/etc/udev/rules.d/52-nut-usbups.rules
    mode=0644
    group=root
    owner=root
  notify:
    - restart nut-driver