# Required variables:
# fspath_pihole_config
# user_pihole
# group_pihole

#inspired by: https://gist.github.com/bendews/e09edfc60e581ec4c686c4b70297f543
# and https://github.com/gsemet/ansible-rpi-pihole

---


- name: Create pihole configuration directory
  become: True
  file:
    name="/etc/pihole"
    state=directory
    owner="pihole"
    group="pihole"
    mode=0775
  tags: pihole

#- name: Create pihole configuration
#  become: True
#  template:
#    src="setupVars.conf.j2"
#    dest="{{ fspath_pihole_config }}/setupVars.conf"
#    owner=root
#    group=root
#    mode=0644
#  register: pihole_config
#  tags: pihole

- stat:
    path: /usr/local/bin/pihole
  register: pihole_binary
  
- set_fact:
    pihole_installed: "{{ pihole_binary.stat.exists | default(false) }}"
  
- name: "Download Pi-Hole installer"
  get_url:
    url: https://install.pi-hole.net
    dest: ~/install-pihole.sh
    mode: 0740
  when: not pihole_installed
  tags: pihole
  
- name: Install Pi-Hole
  shell: "~/install-pihole.sh --unattended"
  register: dbg_install_pihole
  when: not pihole_installed
  tags: pihole
  
- name: Install inotify
  apt:
    name: inotify-tools